//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICU_DB_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int score_id { get; set; }
        public int poid { get; set; }
        public int patid { get; set; }
        public Nullable<int> mms_score { get; set; }
        public Nullable<int> cpa_total { get; set; }
        public Nullable<int> mrc_total { get; set; }
        public Nullable<int> sofa_total { get; set; }
        public string diagnosis { get; set; }
    }
}
